import type { Metadata } from "next"

export const rootMetadata: Metadata = {
  title: {
    default: "Md. Asif",
    template: "%s | Md. Asif",
  },
  description:
    "Frontend Software Engineer with solid experience delivering responsive applications using React.js and Next.js. Skilled in Agile methodologies and REST API integration, with a track record of enhancing UI reliability and performance through effective debugging and optimization. Committed to continuous learning and collaborative development.",
  keywords: [
    "Web Applications",
    "Software Development",
    "Software Design and Architecture",
    "Full-Stack Web Development (React/Node.js)",
    "Cross-Platform Mobile Development",
    "Cloud & DevOps Fundamentals (AWS/Docker)",
    "API Design (REST & GraphQL)",
    "Agile Project Management (Scrum)",
    "Data Structures and Algorithm Design",
    "Technical Documentation",
    "User-Centric Design Principles (UX/UI)",
    "Continuous Integration/Continuous Deployment (CI/CD)",
    "Next.js",
    "React",
    "TypeScript",
    "JavaScript",
    "Frontend",
    "Web Development",
    "Software Engineer",
    "Md. Asif",
    "Portfolio",
    "Blog",
    "Projects",
    "Tech Enthusiast",
    "Open Source",
    "UI/UX",
    "Performance Optimization",
    "Agile",
    "REST API",
    "Responsive Design",
    "Debugging",
    "Collaboration",
    "Continuous Learning",
    "Innovation",
    "Problem Solving",
    "Team Player",
    "Tech Community",
    "Coding",
    "Development",
  ],
  authors: [{ name: "Md. Asif" }],
  creator: "Md. Asif",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "http://muhammadasif.me",
    title: "Md. Asif",
    description:
      "Frontend Software Engineer with solid experience delivering responsive applications using React.js and Next.js. Skilled in Agile methodologies and REST API integration, with a track record of enhancing UI reliability and performance through effective debugging and optimization. Committed to continuous learning and collaborative development.",
    siteName: "Md. Asif",
  },
  twitter: {
    card: "summary_large_image",
    title: "Md. Asif",
    description:
      "Frontend Software Engineer with solid experience delivering responsive applications using React.js and Next.js. Skilled in Agile methodologies and REST API integration, with a track record of enhancing UI reliability and performance through effective debugging and optimization. Committed to continuous learning and collaborative development.",
    creator: "@mdasif-me",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
}
