export const core_skills: string[] = [
  "Software Design and Architecture",
  "Full-Stack Web Development (React/Node.js)",
  "Cross-Platform Mobile Development",
  "Cloud & DevOps Fundamentals (AWS/Docker)",
  "API Design (REST & GraphQL)",
  "Agile Project Management (Scrum)",
  "Data Structures and Algorithm Design",
  "Technical Documentation",
  "User-Centric Design Principles (UX/UI)",
  "Continuous Integration/Continuous Deployment (CI/CD)",
  "Software Design and Architecture",
  "Full-Stack Web Development (React/Node.js)",
  "Cross-Platform Mobile Development",
  "Cloud & DevOps Fundamentals (AWS/Docker)",
  "API Design (REST & GraphQL)",
  "Agile Project Management (Scrum)",
  "Data Structures and Algorithm Design",
  "Technical Documentation",
  "User-Centric Design Principles (UX/UI)",
  "Continuous Integration/Continuous Deployment (CI/CD)",
]
